// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfb2lL516JA4spkAqpjhSGEl-wsDTJcc4',
    appId: '1:289963014447:web:292d904fa704051d6dc9da',
    messagingSenderId: '289963014447',
    projectId: 'chatapp-a7219',
    authDomain: 'chatapp-a7219.firebaseapp.com',
    storageBucket: 'chatapp-a7219.appspot.com',
    measurementId: 'G-Z6VYRTXJLK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvYBtZoZFIS_TJbBi1In5NUF5LeEtG3uE',
    appId: '1:289963014447:ios:5aaf54b658604ac46dc9da',
    messagingSenderId: '289963014447',
    projectId: 'chatapp-a7219',
    storageBucket: 'chatapp-a7219.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvYBtZoZFIS_TJbBi1In5NUF5LeEtG3uE',
    appId: '1:289963014447:ios:5aaf54b658604ac46dc9da',
    messagingSenderId: '289963014447',
    projectId: 'chatapp-a7219',
    storageBucket: 'chatapp-a7219.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfb2lL516JA4spkAqpjhSGEl-wsDTJcc4',
    appId: '1:289963014447:web:b429be7644da30f86dc9da',
    messagingSenderId: '289963014447',
    projectId: 'chatapp-a7219',
    authDomain: 'chatapp-a7219.firebaseapp.com',
    storageBucket: 'chatapp-a7219.appspot.com',
    measurementId: 'G-KQWGM7P1X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpYwikelMxXV3x_ZBFFI4g82x2ksB6OfY',
    appId: '1:289963014447:android:2f0e51a9dbd895956dc9da',
    messagingSenderId: '289963014447',
    projectId: 'chatapp-a7219',
    databaseURL: 'https://chatapp-a7219-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-a7219.appspot.com',
  );

}